### ISSUE TITLE
Implement logic for Autonomous

### ISSUE THREAD

**Issue by Ben1492** [TeamCautionRobotics/2018-FRC-robot#31]
We really don't want to go across the field since we have no way of avoiding other robots.

Center Start:  
      1. Deploy to whichever side of the switch is ours. or
      2. Cross the line to the opposite side and don't deploy

Right or Left start:
      1. If the switch on the side where we start is our alliances color, deploy at that switch.
      2. If it is not our color, move across the line on the same side we are staring on.   
     (ie, if we are on the right and the right switch is our color, go deploy the cube there, if it's not our color just go forward but don't deploy.)
      3. Optionally just cross the line but don't deploy no matter what the state of the Switch.
       4. Optionally deploy the cube to the scale if we think we can do it.  I'm not confident yet in the reliability of the lift to make it to the scale.

**Comment by docprofsky** [comment]
For @TaeSeanDo's work in [Autonomous-Missions](/TeamCautionRobotics/2018-FRC-robot/tree/Autonomous-Missions) @ ef9585cac5b4aa58a4e858fabdd14e8c7abde806, some changes need to be made:
- [x] The `startingPositionChooser` needs to be poutted on the SmartDashboard.
- [x] The `startingPositionChooser` needs to have a default value of center.
- [x] The `autoFieldElementChooser` needs to be poutted on the SmartDashboard.
- [x] The `autoFieldElementChooser` needs to have a default value of swittch.
- [x] The `HashMap<String, Mission> missions` needs to be initialized or removed. (probably removed)
