### ISSUE TITLE
Arm Intake Driver Controls

### ISSUE THREAD

**Issue by ConnorNail** [TeamCautionRobotics/2018-FRC-robot#43]
3 Positions for Arm
Up (Inside the Robot): Default position. The intake should always return to this position
45 Degrees: Controlled by manipulator remote. Ask Alex for button location.
Down (Intaking): Controlled by the button that is closest to the driver and on top of the joystick* on the left joystick. Should override 45 Degree position.

When either the Down or 45 Degree buttons are held the arm is in that position. When the buttons are released the arm should return to its default Up position.

*I don't remember what number corresponds to this button

**Comment by TaeSeanDo** [comment]
The button should be a toggle, correct?

**Comment by TaeSeanDo** [comment]
@TheSwank Do you want the button for intake rotation to be a toggle? Also where do you want the button?
