### ISSUE TITLE
Code controls to turn the power cubes effectively

### ISSUE THREAD

**Issue by TaeSeanDo** [TeamCautionRobotics/2018-FRC-robot#9]
Bumpers should turn the cubes briefly for a fixed amount of time with the click of a bumper. The motor values should run in the opposite directions at different values from each other.

**Comment by docprofsky** [comment]
The current software works, but the tension on the intake rollers is too low. Once this is fixed, additional testing can be done.

**Comment by docprofsky** [comment]
We tested this. It may need adjustment, but probably not.
